ARG PYVERSION=3.11
ARG RELEASE=alpine3.18

FROM python:$PYVERSION-$RELEASE as build

RUN set -ex \
    && apk update \
    && apk add --no-cache build-base libffi-dev \
    && pip install \
        --no-cache-dir \
        --disable-pip-version-check \
            wheel \
    && mkdir /wheels \
    && pip wheel --wheel-dir=/wheels gevent


FROM python:$PYVERSION-$RELEASE

LABEL maintainer="Kirill Vercetti <office@kyzima-spb.com>"

STOPSIGNAL SIGINT

EXPOSE 5000

ENV PYTHONPATH "/python_packages:/app"
ENV USER_UID 1000
ENV USER_GID 1000
ENV FLASK_APP app:app

WORKDIR /app

COPY --from=build /wheels /wheels

RUN set -ex \
    && apk update \
    && apk add --no-cache \
        bash \
        shadow \
        gettext \
        su-exec \
    && pip install \
        --no-index \
        --find-links=/wheels \
        --no-cache-dir \
        --disable-pip-version-check \
            gevent \
    && pip install \
        --no-cache-dir \
        --disable-pip-version-check \
            flask \
            gunicorn \
            pythoninfo \
    && rm -rf /wheels

RUN set -x \
    && addgroup -g 1000 user \
    && adduser -u 1000 -G user -s /bin/sh -D user

COPY --from=kyzimaspb/useful /apps/compver/compver.sh /usr/local/bin/
COPY --from=kyzimaspb/useful /apps/switch-user/switch-user.sh /usr/local/bin/

COPY ./root /

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["flask", "run"]
