name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base:
          - slim-bullseye
          - bullseye
          - slim-buster
          - buster
          - slim-stretch
          - stretch
          - alpine3.13
          - alpine3.14
        version:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
    steps:
      -
        name: Check Dokerfile existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "./${{ matrix.version }}/${{ matrix.base }}/Dockerfile"
      -
        name: Show tag
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "${{ matrix.version }}-${{ matrix.base }}"
    