name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base:
          - slim-bullseye
          - bullseye
          - slim-buster
          - buster
          - alpine3.13
          - alpine3.14
        version:
          - "3.10"
          - "3.9"
          - "3.8"
    steps:
      -
        name: Check Out Repo
        uses: actions/checkout@v2
      -
        name: Check Dokerfile existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "${{ matrix.version }}/${{ matrix.base }}/Dockerfile"
      -
        name: Exit
        if: steps.check_files.outputs.files_exists != 'true'
        run: exit 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
    