name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [
          slim-bullseye, bullseye,
          slim-buster, buster,
          slim-stretch, stretch,
          alpine3.13, alpine3.14
        ]
        version: ["3.8", "3.9", "3.10"]
    steps:
      -
        name: Show tag
        run: echo "${{ matrix.version }}-${{ matrix.base }}"
    